using a release jar

diff --git a/bin/apalache-mc b/bin/apalache-mc
--- a/bin/apalache-mc
+++ b/bin/apalache-mc
@@ -7,11 +7,16 @@
 DIR=`dirname $0`
 DIR=`cd "$DIR/.."; pwd`
 echo "# Tool home: $DIR"
-JAR=`find "$DIR/mod-distribution/target/" -name "distribution-*-jar-with-dependencies.jar" | head -n 1`
+# try to find a release file first
+JAR=`find "$DIR" -depth 1 -name "apalache-bmcmt-*-with-dependencies.jar" | head -n 1`
 
 if [ ! -f "$JAR" ]; then
-    echo "ERROR: Distribution jar not found. Did you run mvn package?"
-    exit 1
+    # try to find a package file
+    JAR=`find "$DIR/mod-distribution/target/" -depth 1 -name "distribution-*-jar-with-dependencies.jar" | head -n 1`
+    if [ ! -f "$JAR" ]; then
+        echo "ERROR: Distribution jar not found. Did you run mvn package?"
+        exit 1
+    fi
 fi
 
 echo "# Package: $JAR"
