DCO remediation commit for Igor Konnov <igor@konnov.phd>
I, Igor Konnov <igor@konnov.phd>, hereby add my Signed-off-by to this commit: 5605e11da061362bcebb3ca2483ee98e0243eea3

Signed-off-by: Igor Konnov <igor@konnov.phd>

diff --git a/.github/workflows/publish-to-maven-central.yml b/.github/workflows/publish-to-maven-central.yml
--- a/.github/workflows/publish-to-maven-central.yml
+++ b/.github/workflows/publish-to-maven-central.yml
@@ -57,7 +57,7 @@ jobs:
 
           if [[ "$RELEASE_TAG" != "$expected_tag" ]]
           then
-              echo "error: release tag $RELEASE_TAG does not match VERSION $version (expected: $expected_tag)" >&2
+              echo "error: version tag $RELEASE_TAG does not match VERSION $version (expected: $expected_tag)" >&2
               exit 1
           fi
 
